myapp/urls.py
from django.urls import path
from myapp.views import index,PostCreate,detail

app_name = 'myapp'

urlpatterns = [
    path('',index,name = 'index'),
    path('create/',PostCreate.as_view(),name = 'create'),
    path('detail/<int:pk>/',detail,name = 'detail'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/',include('registration.backends.default.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TimeStamp(models.Model):
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	user = models.ForeignKey(User,on_delete = models.CASCADE)

	class Meta:
		abstract = True

class Post(TimeStamp):
	title = models.CharField(max_length = 100)
	description = models.TextField()
	image = models.ImageField(upload_to = '')
	likes = models.IntegerField(default = 0)

	def __str__(self):
		return self.title

class Comment(TimeStamp):
	post = models.ForeignKey(Post,on_delete = models.CASCADE)
	comment = models.TextField()

	def __str__(self):
		return self.comment

myapp/forms.py
from django import forms
from myapp.models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']

myapp/views.py
from django.shortcuts import render,reverse
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse,HttpRequest
from myapp.models import Post,Comment
from django.views.generic.edit import CreateView
from myapp.forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

# Create your views here.
def index(request):
	# process the data
	posts = Post.objects.all()
	context = {'posts':posts}
	return render(request,'index.html',context)
class PostCreate(CreateView):
	model = Post
	fields = ['title','description','image']
	template_name = 'create.html'
	success_url = '/'

	def form_valid(self,form):
		form.instance.user = self.request.user
		return super().form_valid(form)

def detail(request,pk):
    p = Post.objects.get(pk = pk)
    comments = Comment.objects.filter(post_id = pk)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            comment = form.cleaned_data['comment']
            c = Comment(post_id = pk,comment = comment,user = request.user)
            c.save()
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('myapp:detail', kwargs = {'pk':pk}))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = CommentForm()

    return render(request, 'detail.html', {'form': form,'p':p,'comments':comments})

myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Food Blog</title>
	<!-- CSS only -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/411101df7a.js" crossorigin="anonymous"></script>
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">FOOD BLOG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'myapp:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:create' %}">Post</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="{{request.user}}" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>&nbsp;
    {% if not user.is_authenticated %} 
    <a class="btn btn-primary" href="{% url 'auth_login' %}">Login</a>
    <a class="btn btn-primary" href="{% url 'registration_register' %}">Register</a>
    {% else %}
    <a class="btn btn-primary" href="{% url 'auth_logout' %}">Logout</a>
    {% endif %}
  </div>
</nav>
<div class="container">
	<br>
	{% block content %}
	<!--content here-->
	{% endblock %}
</div>

</body>
</html>

myapp/templates/create.html
{% extends 'base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Save">
</form>
{% endblock %}

myapp/templates/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	<div class="col-6">

	<span id="title">{{p.title}}</span><br>
	{{p.description}}<br>
	<img src="{{p.image.url}}" width="300" height="300"><br>
	
	</div>

	<div class="col-6">

	<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
	</form>

	</div>

</div>
	<br><br><br>
	<h6>Comments:</h6>
    
    {% for i in comments %}

    {{forloop.counter}} - {{i.comment}} <br>
    at {{i.created_at}} by {{i.user}} <br>

    {% endfor %}

</div>

{% endblock %}

myapp/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        {% for post in posts %}
        <div class="col-md-6 mb-4">
            <div class="card">
                <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'myapp:detail' post.id %}">{{ post.title }}</a></h5>
                    <p class="card-text">{{ post.description }}</p>
                    <p class="card-text">
                        <small class="text-muted">
                            {{ post.created_at|date:"F d, Y" }} by {{ post.user.username }}
                        </small>
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}